server:
  #  网关端口
  port: 9000

eureka:
  client:
    service-url:
      defaultZone:  http://@localhost:8761/eureka/,http://@localhost:8762/eureka/

zuul:
  routes:
    order:
      path: /order/**
      serviceId: order  #如果是/order/**路径下的请求，则跳转到order微服务中
