server:
#  网关端口
  port: 9002
  session-timeout: 1800

spring:
  application:
    name: hsst-zuul

eureka:
  client:
    service-url:
      defaultZone:  http://user:123456@127.0.0.1:9011/eureka/,http://user:123456@127.0.0.1:9012/eureka/

zuul:
  routes:
    hsst-water:
      path: /hsst-water/**
      serviceId: hsst-water  #如果是/water/**路径下的请求，则跳转到hsst-water微服务中
    hsst-air:
      path: /hsst-air/**
      serviceId: hsst-air
    hsst-land:
      path: / hsst-earth/**
      serviceId:  hsst-earth
    hsst-forest:
      path: /hsst-forest/**
      serviceId: hsst-forest
    hsst-combine:
      path: /hsst-combine/**
      serviceId: hsst-combine
    hsst-audit:
      path: /hsst-audit/**
      serviceId: hsst-audit
    hsst-scheduled:
      path: /hsst-scheduled/**
      serviceId: hsst-scheduled
    hsst-rule:
      path: /hsst-rule/**
      serviceId: hsst-rule