server:
#  网关端口
  port: 9001

spring:
  application:
    name: zuul
#  redis:
#      host: 192.128.15.202
#      port: 6379
#      timeout: 300
#      password: tepia
#      database: 2
#      pool:
#        # 连接池中的最大空闲连接
#        max-idle: 8
#        # 连接池中的最小空闲连接
#        min-idle: 10
#        # 连接池最大连接数（使用负值表示没有限制）
#        max-active: 100
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1
eureka:
  client:
    service-url:
      defaultZone:  http://@localhost:8761/eureka/

zuul:
  routes:
    order:
      path: /order/**
      serviceId: order  #如果是/order/**路径下的请求，则跳转到order微服务中

logging:
  level: