# 集群模式，本机测试需要修改host
# 127.0.0.1 peer1
# 127.0.0.1 peer2
server:
  port: 8761

spring:
  application:
    name: eurake

eureka:
  instance:
    hostname: peer1
  client:
    # 设置为true，因为集群需要相互注册,默认为true，
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://@peer2:8762/eureka/