# 集群模式，需要修改host
# 127.0.0.1 peer1
# 127.0.0.1 peer2
server:
  port: 8761

spring:
  application:
    name: hsst-eurake

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://user:123456@127.0.0.1:8762/eureka/