server:
  port: 9010

spring:
  datasource:
    url: jdbc:mysql://localhost/test?useSSL=false&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: cyxcwj

  jpa:
    database: mysql
    show-sql: true
    open-in-view: true

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true     #以IP地址注册到服务中心，相互注册使用IP地址,解决集群服务重名问题，IP不同即可重复注册同一服务
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
